/*
 * Generated by Bluespec Compiler (build 6a8cedf)
 * 
 * On Thu May  7 13:38:37 CST 2020
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkCPU_RegFile_h__
#define __mkCPU_RegFile_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkCPU_RegFile module */
class MOD_mkCPU_RegFile : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_RegFile<tUInt8,tUInt32> INST_regfile;
  MOD_Reg<tUInt8> INST_rg_j;
  MOD_Reg<tUInt8> INST_rg_state;
 
 /* Constructor */
 public:
  MOD_mkCPU_RegFile(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUInt8 PORT_EN_write_rd;
  tUInt8 PORT_read_rs1_rs1;
  tUInt8 PORT_read_rs2_rs2;
  tUInt8 PORT_write_rd_rd;
  tUInt32 PORT_write_rd_rd_val;
  tUInt32 PORT_read_rs1;
  tUInt8 PORT_RDY_read_rs1;
  tUInt32 PORT_read_rs2;
  tUInt8 PORT_RDY_read_rs2;
  tUInt8 PORT_RDY_write_rd;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_write_rd;
  tUInt8 DEF_WILL_FIRE_RL_rl_reset_loop;
  tUInt8 DEF_CAN_FIRE_RL_rl_reset_loop;
  tUInt8 DEF_WILL_FIRE_RL_rl_reset_start;
  tUInt8 DEF_CAN_FIRE_RL_rl_reset_start;
  tUInt8 DEF_CAN_FIRE_write_rd;
  tUInt8 DEF_CAN_FIRE_read_rs2;
  tUInt8 DEF_CAN_FIRE_read_rs1;
 
 /* Local definitions */
 private:
 
 /* Rules */
 public:
  void RL_rl_reset_start();
  void RL_rl_reset_loop();
 
 /* Methods */
 public:
  tUInt32 METH_read_rs1(tUInt8 ARG_read_rs1_rs1);
  tUInt8 METH_RDY_read_rs1();
  tUInt32 METH_read_rs2(tUInt8 ARG_read_rs2_rs2);
  tUInt8 METH_RDY_read_rs2();
  void METH_write_rd(tUInt8 ARG_write_rd_rd, tUInt32 ARG_write_rd_rd_val);
  tUInt8 METH_RDY_write_rd();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkCPU_RegFile &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkCPU_RegFile &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkCPU_RegFile &backing);
};

#endif /* ifndef __mkCPU_RegFile_h__ */
